ZetaShare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontliner.urls', namespace='main')),
    path('app/', include('zets.urls', namespace='zets')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontliner/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('sign-up/', register, name='register'),
    path('login/', login_request, name='login'),
    path('logout/', logout_request, name='logout'),
    path('activate/<uidb64>/<token>/', activate_account, name='activate'),
    path('new-password/', change_password, name='changePassword'),
    path('password-mail/', password_change_mail, name='PasswordMail'),
    path('password/<uidb64>/<token>/', password_validation, name='password'),
    path('social-auth/', social_auth, name='social')
]

zets/urls.py
from django.urls import path
from .tokens import linkedin_data
from .views import *

app_name = 'zets'

urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('profile/', user_profile, name='profile'),
    path('connect-app/', connections, name='connectApp'),
    path('create-zets/', card, name='card'),
    path('linkedin-oauth2/callback/', linkedin_data, name="linkedin"),
    path('connected/fetch/', fetch_connect_app),
    path('connected/delete/', delete_connect_app),
    path('connected/custom-page/', custom_page_name)
    ]

zets/models.py
from django.db import models
from django.contrib.auth.models import User


provider = [
    ('Facebook', 'Facebook'),
    ('Google', 'Google'),
    ('LinkedIn', 'LinkedIn')
]

status = [
    ('Completed', 'Completed'),
    ('Pending', 'Pending'),
    ('Failed', 'Failed')
]

visibility = [
    ('CONNECTIONS', 'CONNECTIONS'),
    ('PUBLIC', 'PUBLIC')
]


class SocialMedia(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    added_on = models.DateTimeField(auto_now_add=True)
    provider = models.CharField(max_length=10, choices=provider)
    social_id = models.CharField(max_length=99)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    profile_pic = models.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.user.username} - {self.provider}'

    class Meta:
        verbose_name_plural = 'Social Accounts'


class Connections(models.Model):
    added_on = models.DateTimeField(auto_now=True)
    social = models.ForeignKey(SocialMedia, on_delete=models.CASCADE)
    posting_id = models.CharField(max_length=99)
    page_name = models.CharField(max_length=30, null=True, blank=True)
    access_token = models.CharField(max_length=360)
    token_expiration_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'{self.social.user.username} - {self.social.provider}'

    class Meta:
        verbose_name_plural = 'Social Connections'


class Posts(models.Model):
    app = models.ForeignKey(Connections, on_delete=models.CASCADE)
    added_on = models.DateTimeField(auto_now_add=True)
    post_on = models.DateTimeField()
    visibility = models.CharField(max_length=11, null=True, blank=True, choices=visibility)
    status = models.CharField(max_length=10, choices=status)

    def __str__(self):
        return f'{self.app.social.user.username} - {self.app.social.provider}'

    class Meta:
        verbose_name_plural = 'Posts'


class PostMedia(models.Model):
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    caption = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return f'{self.post.app.social.user.username} - {self.post.app.social.provider}'

    class Meta:
        verbose_name_plural = 'Posts Media '

zets/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password')

    def clean_username(self):
        instance = self.instance
        user = self.cleaned_data['username']
        qs = User.objects.filter(username=user)
        if instance is not None:
            qs = qs.exclude(pk=instance.pk)
        if qs.exists():
            raise forms.ValidationError('User Already Exists')
        return user

    def clean_email(self):
        instance = self.instance
        email = self.cleaned_data['email']
        qs = User.objects.filter(email=email)
        if instance is not None:
            qs = qs.exclude(pk=instance.pk)
        if qs.exists():
            raise forms.ValidationError('Email Already Exists')
        return email

zets/views.py
import datetime
import threading
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .forms import EditProfileForm
from .models import Connections
from .tokens import facebook_data
from .utils import post_linkedin, post_facebook


@login_required(login_url='main:home')
def dashboard(request):
    return render(request, 'zets/dashboard.html')


@login_required(login_url='main:home')
def user_profile(request):
    form = EditProfileForm(request.POST or None, instance=request.user)
    if form.is_valid():
        form.save()
        messages.success(request, 'Changes Saved Successfully')
        return redirect('zets:profile')
    else:
        print(form.errors)
        messages.error(request, form.errors)
    return render(request, 'zets/profile.html', {'form': form})


@login_required(login_url='main:home')
def connections(request):
    if request.method == 'POST':
        facebook_data(request)
        return JsonResponse({'msg': 'Connect App Done'})

    return render(request, 'zets/CreateApp.html')


@login_required(login_url='main:home')
def card(request):
    if request.method == 'POST':
        facebook = [force_text(urlsafe_base64_decode(x)) for x in request.POST.getlist('app_Facebook[]')]
        linkedin = [force_text(urlsafe_base64_decode(x)) for x in request.POST.getlist('app_LinkedIn[]')]
        caption = request.POST.get('post_caption')
        img = request.FILES.get('post_img.name')

        print(facebook, linkedin, caption, img)

        # caption = request.POST.get('caption')
        # image = request.FILES.get('postimg')
        #
        # media = [caption, image]
        #
        # # posting on Facebook
        # if facebook:
        #     fb_post = threading.Thread(target=post_facebook, args=[request, facebook, media])
        #     fb_post.start()
        #
        # # posting on LinkedIn
        # if linkedin:
        #     linkedin_post = threading.Thread(target=post_linkedin, args=[request, linkedin, media])
        #     linkedin_post.start()
        #
        # print('Posted')
    return render(request, 'zets/card.html')


@login_required(login_url='main:home')
def fetch_connect_app(request):
    data = []

    try:
        fb_qs = Connections.objects.filter(social__user=request.user, social__provider='Facebook')

        for face in fb_qs:
            facebook = {
                'provider': 'Facebook',
                'added_on': face.added_on.date(),
                'posting_id': urlsafe_base64_encode(force_bytes(face.posting_id)),
                'page_name': face.page_name,
            }
            data.append(facebook)

    except Connections.DoesNotExist:
        pass

    try:
        link_qs = Connections.objects.filter(social__user=request.user, social__provider='LinkedIn')

        for link in link_qs:
            linkedin = {
                'provider': 'LinkedIn',
                'added_on': link.added_on.date(),
                'posting_id': urlsafe_base64_encode(force_bytes(link.posting_id)),
                'page_name': link.page_name,
                'token_expiration': link.token_expiration_date
            }
            data.append(linkedin)

    except Connections.DoesNotExist:
        pass

    return JsonResponse({'data': data, 'today': datetime.datetime.now().date()})


@login_required(login_url='main:home')
def delete_connect_app(request):
    posting_id = force_text(urlsafe_base64_decode(request.POST.get('pid')))
    qs = Connections.objects.get(posting_id=posting_id, social__user=request.user)
    qs.delete()

    data = fetch_connect_app(request)
    return data


@login_required(login_url='main:home')
def custom_page_name(request):
    page_name = request.POST.get('page_name'),
    pid = force_text(urlsafe_base64_decode(request.POST.get('pid')))
    qs = Connections.objects.get(social__user=request.user, posting_id=pid)
    qs.page_name = page_name[0]
    qs.save()
    return JsonResponse({'msg': 'Complete'}, status=201)

templates/zets/CreateApp.html
{% extends 'zets/app-index.html' %}
{%  load static %}

{% block title %}Connect | ZetaShare{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/CreateApp.css' %}">
{% endblock %}

{% block content %}
<div class="main-app">
    <div class="create-app">
        <h1 class="title text-muted">Choose Your Apps To Connect</h1>
        <div class="app-container">
            <div class="container">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="card my-4">
                            <!-- facebook -->
                            <div class="app-img">
                                <div class="img-bg" style="background-color: #fcc3cd;">
                                    <img src="{% static 'images/facebook.png' %}" alt="facebook">
                                </div>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">Facebook</h5>
                                <button class="btn btn-primary my-3" id="fbconnect"
                                    onclick="CreateFacebookApp()">Connect Your App</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="card my-4">
                            <!-- instagram -->
                            <div class="app-img">
                                <div class="img-bg" style="background-color: #FFEB3B;">
                                    <img src="{% static 'images/instagram.png' %}" alt="instagram">
                                </div>
                            </div>

                            <div class="card-body">
                                <h5 class="card-title">Instagram</h5>
                                <button class="btn btn-primary my-3">Connect Your App</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="card my-4">
                            <!-- Linkdin -->
                            <div class="app-img">
                                <div class="img-bg" style="background-color: #1fe0ff8c;">
                                    <img src="{% static 'images/linkedin.png' %}" alt="linkedin">
                                </div>
                            </div>

                            <div class="card-body">
                                <h5 class="card-title">Linkdin</h5>
                                <button class="btn btn-primary my-3" onclick="linkedInAuth()">
                                    Connect Your App
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="card my-4">
                            <!-- Twitter -->
                            <div class="app-img">
                                <div class="img-bg" style="background-color: #6bdb4f8c;">
                                    <img src="{% static 'images/twitter.png' %}" alt="Twitter">
                                </div>
                            </div>

                            <div class="card-body">
                                <h5 class="card-title">Twitter</h5>
                                <button class="btn btn-primary my-3">Connect Your App</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="createdApp mb-5">
        <h1 class="title text-muted">Your Connected App</h1>
        <ul class="applist" id="setup-app" style="list-style: none;">
            
        </ul>
    </div>
</div>
{% endblock %}

templates/zets/app-index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>


    <!-- css files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    {% block style %}
    {% endblock %}


    <!-- icons -->
    <link rel="stylesheet" href="{% static 'css/boxicons.min.css' %}">


    <!-- script -->
    <script src="{% static 'js/jquery-3.4.0.min.js' %}"></script>
    <script src="{% static 'js/connectapp.js' %}"></script>
    
</head>

<body>
    <div class="wrapper">
        <div class="sidebar-container h-100">
            <div class="sidebar-body h-100">
                <div class="sidebar-content">
                    <div class="userProfile py-4">
                        <!-- <h1 class="site-brand">ZetaShare</h1> -->
                    </div>
                    <ul class="data">
                        <li class="mx-2 mb-4">
                            <a href="{% url 'zets:dashboard' %}" class="active">
                                <i class='bx bxl-squarespace' style="font-size: 30px;"></i>
                                <span class="text-muted ml-3">Dashboard</span>
                            </a>
                        </li>
                        <li class="mx-2 mb-4">
                            <a href="{% url 'zets:connectApp' %}">
                                <i class='bx bx-link' style="font-size: 30px;"></i>
                                <span class="text-muted ml-3">Connect App</span>
                            </a>
                        </li>
                        <li class="mx-2 mb-4">
                            <a href="{% url 'zets:card' %}">
                                <i class='bx bxs-collection' style="font-size: 30px;"></i>
                                <span class="text-muted ml-3">Create Post</span>
                            </a>
                        </li>
                        <li class="mx-2 mb-4">
                            <a href="#">
                                <i class='bx bxs-bell bx-tada' style="font-size: 30px;"></i>
                                <span class="text-muted ml-3">Schedule</span>
                            </a>
                        </li>
                        <li class="mx-2 mb-4">
                            <a href="#">
                                <i class='bx bxs-phone bx-tada' style="font-size: 30px;"></i>
                                <span class="text-muted ml-3">Contact</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>


        <!-- main menu -->
        <div class="main-menu">
            <header>
                <nav class="navbar navbar-expand-lg navbar-light bg-light" style="justify-content: space-between;">
                    <a class="navbar-brand" href='{% url "main:home" %}'>ZetaShare</a>
                    <!-- on user login profile  -->
                    <div class="btn-group" id="user-info">
                        <button type="button" class="dropdown" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false" style="border: 0;background: #f8f9fa;outline:none;cursor: pointer;">
                            <img src="{% static 'images/profile.png' %}" alt="profilepic" id="user_profile_img"
                                width="50px" height="50px" style="border: 3px solid #e0e0e0;border-radius: 50%;">
                            <span class="username" id="logged_user_name">{{ user.first_name }} {{ user.last_name }}</span>
                            <i class="bx bx-chevron-down" style="color:#151111"></i>
                        </button>

                        <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end"
                            style="position: absolute;will-change: transform; top: 0; left: 0; transform: translate3d(-22px, 56px, 0px);">

                           <a class="dropdown-item" href="{% url 'zets:profile' %}">
                                <i class="bx bx-user bx-flip-horizontal"></i>
                                <span>Profile</span>
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="bx bx-wrench bx-tada bx-flip-horizontal"></i>
                                <span>Setting</span>
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item glog" href="{% url 'main:logout' %}" style="color: red;">
                                <i class="bx bx-power-off bx-flip-horizontal"></i>
                                <span>Logout</span>
                            </a>
                        </div>
                    </div>
                </nav>
            </header>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" style="margin-left: 46px; margin-right: 20px;">
                    {{ message }}
                </div>
                {% endfor %}
            </ul>
            {% endif %}


            {% block content %}
            {% endblock %}
        </div>
    </div>



    <!-- bootstrap and jquery -->

    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/zets.js' %}"></script>
    <script src="{% static 'js/image-compressor.js' %}"></script>
    {% block script %}
    {% endblock %}

</body>

</html>

templates/zets/card.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>card</title>

    <!-- bootstrap css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- boxicon icon css -->
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

    <style>
        .button_upload {
            background: white;
            position: absolute;
            bottom: 225px;
            right: 25px;
            z-index: 100;
            box-shadow: 0 0 3px 1px #d0c8c8;
            padding: 0 6px;
            border-radius: 50%;
        }

        .button_upload label {
            cursor: pointer;
        }

        #image_preview {
            height: 15em;
            object-fit: fill;
            background: #f66cc3;
        }

        #postcontent {
            width: 100%;
            resize: none;
            font-size: 12px;
            background: #f8f8ed;
            border-color: #f0eaea;
            outline: none;
        }

        .social-icon button {
            outline: none;
            padding: 0;
            box-shadow: none;

        }

        .social-icon button:focus {
            box-shadow: none;
        }

        #checked {
            font-weight: 900;
            color: #167f3a;
            bottom: 28px;
            font-size: 21px;
            z-index: 150;
            position: absolute;
            margin: -3px -10px;
        }
    </style>
</head>



<body>
    <div class="wrapper">
        <form action="" id="post-form">
            <!-- card for posting image -->
            <div class="card my-5" style="width: 18.5em;">
                <img src="" id="image_preview">

                </img>
                <div class="button_upload" type="button">
                    <input type="file" name="postimage" id="post" style="display: none;">
                    <label for="post" role="button" class="my-0" onload="imagePreview()"> <i
                            class='bx bx-upload'></i></label>
                </div>
                <hr class="my-0">
                <div class="card-body p-3">
                    <textarea name="postcontent" id="postcontent" rows="5"
                        placeholder="Write your post caption..."></textarea>

                    <h6 class="card-title text-muted">Also Share On</h6>
                    <div class="social-icon float-sm-right">
                        <button class="btn btn-default" type="button" onclick="social_selected(this)">
                            <i class='bx bxl-facebook-circle' style='color:#ae9033;font-size: 26px;'></i>
                        </button>
                        <button class="btn btn-default" type="button" onclick="social_selected(this)">
                            <i class='bx bxl-instagram' style='color:#ae9033;font-size: 26px;'></i>
                        </button>
                        <button class="btn btn-default" type="button" onclick="social_selected(this)">
                            <i class='bx bxl-twitter' style='color:#ae9033;font-size: 26px;'></i>
                        </button>
                    </div>

                </div>
                <div class="btn btn-primary float-sm-right">Post</div>
            </div>
        </form>
    </div>



    <!-- bootstrap javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <script>

        $('#post').change(function () {
            imagePreview(this)
        })
        function imagePreview(file) {
            if (file.files && file.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    document.getElementById('image_preview').setAttribute('src', e.target.result)
                }

                reader.readAsDataURL(file.files[0]); // convert to base64 string


            }
        }

        function social_selected(ref) {
            console.log(ref.firstElementChild.style.color)
            if (ref.firstElementChild.style.color != "rgb(222, 221, 219)") {
                ref.firstElementChild.style.color = "#dedddb"
                const ele = document.createElement('i')
                ele.setAttribute('class', 'bx bx-check')
                ele.setAttribute('id', 'checked')
                ref.appendChild(ele)
                console.log('if block')
            }
            else {
                console.log('else block')
                ref.firstElementChild.style.color = "#ae9033"
                ref.lastElementChild.remove()
            }
        }

    </script>
</body>

</html>

templates/zets/change-password.html
{% extends 'zets/app-index.html' %}
{%  load static %}
{% block title %}Change Password | ZetaShare{% endblock %}

{% block content %}
    <form method="post" action="{% url 'main:changePassword' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Change Password</button>
    </form>
{% endblock %}

templates/zets/dashboard.html
{% extends 'zets/app-index.html' %}
{%  load static %}
{% block title %}Home | ZetaShare{% endblock %}

{% block content %}
    <h1>Hi, {{ user.first_name }}! Welcome to ZetaShare</h1>
{% endblock %}

templates/zets/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- css files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">

    <!-- icons -->
    <link rel="stylesheet" href="{% static 'css/boxicons.min.css' %}">

</head>

<body>
    <div class="wrapper">
        <div class="sidebar-container h-100">
            <div class="sidebar-body h-100">
                <div class="sidebar-content">
                    <div class="userProfile py-4">
                        <!-- <h1 class="site-brand">ZetaShare</h1> -->
                    </div>
                    <ul class="data">
                        <li class="mx-2 mb-4">
                            <a href="{% url 'main:dashboard' %}" class="active">
                                <i class='bx bxl-squarespace' style="font-size: 30px;"></i>
                                <span class="text-muted ml-3">Dashboard</span>
                            </a>
                        </li>
                        <li class="mx-2 mb-4">
                            <a href="#">
                                <i class='bx bx-link' style="font-size: 30px;"></i>
                                <span class="text-muted ml-3">Connect App</span>
                            </a>
                        </li>
                        <li class="mx-2 mb-4">
                            <a href="#">
                                <i class='bx bxs-collection' style="font-size: 30px;"></i>
                                <span class="text-muted ml-3">Create Post</span>
                            </a>
                        </li>
                        <li class="mx-2 mb-4">
                            <a href="#">
                                <i class='bx bxs-bell bx-tada' style="font-size: 30px;"></i>
                                <span class="text-muted ml-3">Schedule</span>
                            </a>
                        </li>
                        <li class="mx-2 mb-4">
                            <a href="#">
                                <i class='bx bxs-phone bx-tada' style="font-size: 30px;"></i>
                                <span class="text-muted ml-3">Contact</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>


        <!-- main menu -->
        <div class="main-menu">
            <header>
                <nav class="navbar navbar-expand-lg navbar-light bg-light" style="justify-content: space-between;">
                    <a class="navbar-brand" href='{% url "main:home" %}'>ZetaShare</a>
                    <!-- on user login profile  -->
                    <div class="btn-group" id="user-info">
                        <button type="button" class="dropdown" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false" style="border: 0;background: #f8f9fa;outline:none;cursor: pointer;">
                            <img src="{% static 'images/profile.png' %}" alt="profilepic" id="user_profile_img"
                                width="50px" height="50px" style="border: 3px solid #e0e0e0;border-radius: 50%;">
                            <span class="username" id="logged_user_name">{{ user.first_name }} {{ user.last_name }}</span>
                            <i class="bx bx-chevron-down" style="color:#151111"></i>
                        </button>

                        <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end"
                            style="position: absolute;will-change: transform; top: 0; left: 0; transform: translate3d(-22px, 56px, 0px);">

                            <a class="dropdown-item" href="{% url 'main:profile' %}">
                                <i class="bx bx-user bx-flip-horizontal"></i>
                                <span>Profile</span>
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="bx bx-wrench bx-tada bx-flip-horizontal"></i>
                                <span>Setting</span>
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item glog" href="{% url 'main:logout' %}" style="color: red;">
                                <i class="bx bx-power-off bx-flip-horizontal"></i>
                                <span>Logout</span>
                            </a>
                        </div>
                    </div>
                </nav>
            </header>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" style="margin-left: 46px; margin-right: 20px;">
                        {{ message }}
                    </div>
                    {% endfor %}
                </ul>
            {% endif %}

            <main style="margin-left: 550px;">
                {% block content %}
                {% endblock %}
            </main>
        </div>
    </div>

    <!-- bootstrap and jquery -->
    <script src="{% static 'js/jquery-3.4.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/myapp.js' %}"></script>
</body>

</html>

templates/zets/profile.html
{% extends 'zets/app-index.html' %}
{%  load static %}
{% block title %}Profile | ZetaShare{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <label for="id_username">Username:</label>
        {{ form.username }}<br>
        <label for="id_first_name">First name: </label>
        {{ form.first_name }}<br>
        <label for="id_last_name">Last name:</label>
        {{ form.last_name }}<br>
        <label for="id_email">Email</label>
        {{ form.email }}<br>

        <a href="#" data-url="{% url 'main:PasswordMail' %}" onclick="passwordMailer(this)">Change Password</a>
        <button type="submit">Save</button>
    </form>
{% endblock %}