ZetaShare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontliner.urls', namespace='main')),
    path('app/', include('zets.urls', namespace='zets')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontliner/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('sign-up/', register, name='register'),
    path('login/', login_request, name='login'),
    path('logout/', logout_request, name='logout'),
    path('activate/<uidb64>/<token>/', activate_account, name='activate'),
    path('new-password/', change_password, name='changePassword'),
    path('password-mail/', password_change_mail, name='PasswordMail'),
    path('password/<uidb64>/<token>/', password_validation, name='password'),
    path('social-auth/', social_auth, name='social')
]

zets/urls.py
from django.urls import path
from .tokens import linkedin_data
from .views import *

app_name = 'zets'

urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('profile/', user_profile, name='profile'),
    path('connect-app/', connections, name='connectApp'),
    path('create-zets/', card, name='card'),
    path('linkedin-oauth2/callback/', linkedin_data, name="linkedin"),
    path('connected/fetch/', fetch_connect_app),
    path('connected/delete/', delete_connect_app),
    path('connected/custom-page/', custom_page_name)
    ]

frontliner/models.py
from django.db import models

# Create your models here.

frontliner/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username or email address'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    def clean(self, *args, **kwargs):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        if username and password:
            try:
                if '@' in username:
                    user = User.objects.get(email=username)
                else:
                    user = User.objects.get(username=username)

                if not user.check_password(raw_password=password):
                    raise forms.ValidationError('Incorrect Password')
                if not user.is_active:
                    raise forms.ValidationError('Please verify your email first')
            except User.DoesNotExist:
                raise forms.ValidationError('User does not exist')


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email', widget=forms.TextInput(attrs={'placeholder': 'Email address'}))
    first_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    last_name = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={'placeholder': 'Surname'}))
    password1 = forms.CharField(label="Password", strip=False, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(label="Confirm Password", strip=False, widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
        }

    def clean_username(self):
        user = self.cleaned_data['username']
        qs = User.objects.filter(username=user)
        if qs.exists():
            raise forms.ValidationError('User Already Exists')
        return user

    def clean_email(self):
        email = self.cleaned_data['email']
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError('Email Already Exists')
        return email

frontliner/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.http import JsonResponse
from django.shortcuts import render, redirect, HttpResponse
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .forms import SignUpForm, LoginForm
from .tokens import account_activation_token, password_change_token
from zets.models import SocialMedia


def home(request):
    if request.user.is_authenticated:
        return redirect('zets:dashboard')
    register_form = SignUpForm
    login_form = LoginForm
    context = {
        'signup': register_form,
        'login': login_form
    }
    return render(request, 'frontliner/index.html', context)


def logout_request(request):
    logout(request)
    messages.info(request, 'Logged Out Successfully')
    return redirect('main:home')


def login_request(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')

            if '@' in username:
                user = User.objects.get(email=username)
            else:
                user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return JsonResponse({'msg': f"Logged in as {username}", 'url': '/app/dashboard/'})

        else:
            return JsonResponse({'error': form.errors}, status=401)

    else:
        return redirect("main:home")


def register(request):
    if request.method == 'POST':
        register_form = SignUpForm(request.POST or None)
        if register_form.is_valid():
            user = register_form.save(commit=False)
            user.is_active = False
            user.save()

            # Email Authentication Process
            current_site = get_current_site(request)
            subject = 'Activate your account'
            message = render_to_string('auth/account_activation_mail.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user)
            })
            user.email_user(subject, message)
            # send_mail(subject, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=True)

            return JsonResponse({'msg': 'Account Created, please confirm your email to complete registration.'})
        else:
            response = JsonResponse({'error': register_form.errors})
            response.status_code = 409
            return response

    else:
        return redirect('main:home')


def activate_account(request, uidb64, token, *args, **kwargs):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)

    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        # user.emailauthentication.email_confirmed = True
        user.save()
        login(request, user)
        messages.success(request, 'Account Successfully Activated')
        return redirect('zets:dashboard')
    else:
        messages.error(request, 'The confirmation link was invalid, possibly because it has already been used.')
        return redirect('main:home')


@login_required(login_url='main:home')
def change_password(request):
    if request.method == 'POST':
        form = SetPasswordForm(data=request.POST or None, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Password Changed Successfully')
            login(request, request.user)
            return redirect('zets:profile')
        else:
            messages.error(request, 'Password miss-match')
            form = SetPasswordForm(request.POST or None)
            return render(request, 'zets/change-password.html', {'form': form})


@login_required(login_url='main:home')
def password_change_mail(request):
    user = User.objects.get(pk=request.user.pk)
    current_site = get_current_site(request)
    subject = 'Password Change Request'
    message = render_to_string('auth/account_change_password.html', {
        'user': user,
        'domain': current_site,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': password_change_token.make_token(user)
    })
    user.email_user(subject, message)
    return JsonResponse({'msg': 'Password Change Link Sent to your registered mail'})


@login_required(login_url='main:home')
def password_validation(request, uidb64, token, *args, **kwargs):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)

    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and password_change_token.check_token(user, token):
        form = SetPasswordForm(request.POST or None)
        return render(request, 'zets/change-password.html', {'form': form})
    else:
        messages.error(request, 'Link already used')
        return redirect('zets:dashboard')


def social_auth(request):
    if request.method == 'POST':
        username = request.POST.get('userId')
        name = request.POST.get('userName').split()
        email = request.POST.get('userEmail')
        provider = request.POST.get('provider')
        profile_pic = request.POST.get('userImg')

        try:
            user = User.objects.get(username=username)
            login(request, user)
            print('login')
            obj = SocialMedia.objects.get(social_id=username, user=request.user)

        except (User.DoesNotExist, SocialMedia.DoesNotExist):
            user = User(username=username, first_name=name[0], last_name=name[1], email=email)
            user.save()
            login(request, user)
            print('signup')
            obj = SocialMedia()

        obj.user = user
        obj.provider = provider
        obj.social_id = username
        obj.first_name = name[0]
        obj.last_name = name[1]
        obj.email = email
        obj.profile_pic = profile_pic
        obj.save()

        return JsonResponse({'msg': 'completed', 'url': '/app/dashboard/'})

templates/frontliner/index.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-signin-client_id"
        content="803712653771-vei0i9qo009ukjluu90mldce8bcmsbnb.apps.googleusercontent.com">
    <title>ZetaShare</title>
    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- icons -->
    <link rel="stylesheet" href="{% static 'css/boxicons.min.css' %}">
    <!-- social authentication -->
    <script src="{% static 'js/socialauth.js' %}"></script>
    <script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script>
    <style>
        @keyframes message {
            0% {
                top: 10px;
            }
            75% {
                top: 75px;
                opacity: 1;
            }
            100% {
                opacity: 0;
                top: 75px;
            }
        }
        .messages {
            animation-name: message;
            animation-duration: 5s;
            top: 75px;
            z-index: 1;
            position: fixed;
            right: 108px;
        }

    </style>
</head>

<body>
    <div class="wrapper">
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href={% url 'main:home' %}>Zeta Share</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav m-auto" id="app-nav">
                        <li class="nav-item active mx-3">
                            <a class="nav-link" href='{% url "main:home" %}'>Home</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link" href="#">About us</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link" href="#">Plans</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link" href="#">Explore</a>
                        </li>
                    </ul>
                    <div class="auth-button" onclick="slidertoggle()">
                        <div class="default-data">

                            <span class="text-muted" style="font-size: 0.8rem; font-weight: 600;">Login/Signup</span>

                        </div>
                    </div>
                </div>
            </nav>
        </header>

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        </ul>
        {% endif %}

        <div class="section-0">
            <div class="login-sidebar h-100">
                <div class="sidebar-position p-4">
                    <div id="sider-data">

                        <div class="auth-data">

                            <form id="auth-data" method="post" data-url={% url 'main:login' %} onsubmit="loginSubmit()">
                                {% csrf_token %}
                                <div class="error">
                                    <p id="userErrLog"
                                        style=" display: none; color: red; position: absolute;font-size: 10px;top: 23px;font-weight: 600;">
                                    </p>
                                    <p id="passwordErrLog"
                                        style=" display: none; color: red; position: absolute;font-size: 10px;top: 90px;font-weight: 600;">
                                    </p>
                                    <p id="emailErrLog"
                                        style=" display: none; color: red; position: absolute;font-size: 10px;top: 146px;font-weight: 600;">
                                    </p>
                                </div>
                                {{ login.username }}
                                {{ login.password }}
                                <button class="authbar-button btn -btn-primary w-100"
                                    style="color:white;background:#cd2828">Login</button>
                                <a href="{% url 'password_reset' %}">Forgot password</a>
                                <a href="#" id='signup'> Sign Up</a>
                            </form>
                        </div>

                        <div class="signup-user">

                            <form id="signup-user" method="post" data-url='{% url 'main:register' %}'>
                                {% csrf_token %}
                                <div class="error">
                                    <p id="userErr"
                                        style=" display: none; color: red; position: absolute;font-size: 10px;top: 90px;font-weight: 600;">
                                    </p>
                                    <p id="emailErr"
                                        style=" display: none; color: red; position: absolute;font-size: 10px;top: 158px;font-weight: 600;">
                                    </p>
                                    <p id="password2err"
                                        style=" display: none; color: red; position: absolute;font-size: 10px;top: 294px;font-weight: 600;">
                                    </p>
                                </div>
                                {{ signup.first_name }}
                                {{ signup.last_name }}
                                {{ signup.username }}
                                {{ signup.email }}
                                {{ signup.password1 }}
                                {{ signup.password2 }}

                                <button class="authbar-button btn -btn-primary w-100"
                                    style="color:white;background:#cd2828">Sign Up</button>

                                <label class="log">Already have an account? <a id="login" class="pl-1">
                                        Login</a></label>
                            </form>
                        </div>




                        <div class="fb-login-button mt-3" data-size="large" data-button-type="continue_with"
                            data-layout="default" data-auto-logout-link="false" data-use-continue-as="false"
                            data-width="" data-scope="email" onLogin="checkLoginState()"></div>

                        <!-- google login button -->
                        <div class="g-signin2 mt-3" id="googleauth"></div>
                    </div>
                </div>
            </div>
        </div>

        <!-- section 1 backgroung image -->

        <div class="section-1">
            <div class="bg-image-container">
                <div class="container-fluid row">
                    <div class="container-content col-sm-6" style="padding: 6rem !important;">
                        <div class="caption">
                            <h1 class="text-color">WELCOME </h1>
                            <h3 class="text-color">TO</h3>
                            <h1 class="text-color"> ZETA SHARE</h1>
                        </div>

                    </div>
                    <div class="col-sm-6">
                        <div class="caption-btn" style="margin-top: 200px;">
                            <div class="btn btn-outline-warning mr-3" style="width: 150px;">SEE PLANS</div>
                            <div class="btn btn-info" style="width: 150px;">GET STARTED</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- bootstrap and jquery -->
    <script src="{% static 'js/jquery-3.4.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/frontliner.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const element = document.querySelector('.messages')
            if (element){
                setInterval(() => {element.remove();}, 5000)
            }
        })
    </script>

</body>

</html>